---
dataset:
 train: /path/to/train
 validation: /path/to/validation
 test: /path/to/test

output:
 model: ./models
 plots: ./plots

training_pref:
 batch_size: 25
 learning_rates:
  - rate: .001
    epoch: 1
  - rate: .0005
    epoch: 20
  - rate: .0001
    epoch: 30
  - rate: .00005
    epoch: 40
  - rate: .00001
    epoch: 45
 max_epochs: 50
 momentum: .9
 patience: 20
 weight_decay: 0.0005
 workers: 1

evaluation_pref:
 batch_size: 100
 names_classes:
  - 'b'
  - 'W-H'
  - 't'
 workers: 1

ssd_settings:
 confidence_threshold: .01
 feature_maps:
  - phi: 46
    eta: 44
  - phi: 22
    eta: 21
 input_dimensions:
  - 2
  - 340
  - 360
 n_classes: 3
 nms: .25
 object_size: 46.
 overlap_threshold: .5
 steps:
  - phi: 8
    eta: 8
  - phi: 17
    eta: 17
 top_k: 100
