---
dataset:
 train:
  - /path/to/train0
  - /path/to/train1
  - /path/to/train2
 validation:
  - /path/to/validation0
  - /path/to/validation1
  - /path/to/validation2
 test:
  - /path/to/test

dataset_misc:
 src_folder: /path/to/source/folder
 size:
  - 30000
  - 12000
  - 90000

output:
 model: ./models
 plots: ./plots

training_pref:
 batch_size_train: 25
 batch_size_validation: 150
 max_epochs: 100
 momentum: .9
 patience: 50
 weight_decay: 0.0005
 workers: 0

evaluation_pref:
 batch_size: 100
 names_classes:
  - 't'
  - 'V'
  - 'H'
 workers: 0

inference_pref:
  batch_sizes:
   - 1
   - 2
   - 4
   - 8
   - 16
   - 32
   - 64
   - 100
  rank: 0
  samples: 300

ssd_settings:
 confidence_threshold: .01
 feature_maps:
  - phi: 46
    eta: 44
  - phi: 22
    eta: 21
 input_dimensions:
  - 3
  - 340
  - 360
 n_classes: 3
 nms: .25
 object_size: 46.
 max_distance: .1
 overlap_threshold: .5
 steps:
  - phi: 8
    eta: 8
  - phi: 17
    eta: 17
 top_k: 100
